### ISSUE TITLE
The results dont match with the reported ones in the paper. 

### ISSUE THREAD

**Issue by trungmanhhuynh** [takumayagi/fpl#7]
Hi @takumayagi, 

I tried to run your codes by using exact given instructions for the proposed model only (cnn_ego_pose_scale) and got the results on First-Person Locomotion Dataset below: 
First-Person Locomotion Dataset

![image](https://user-images.githubusercontent.com/13492723/70113973-fcd38180-1617-11ea-8204-6ce7a01fdd29.png)

If I take averages of all splits, it clearly that it could not be the same as the number you reported in your paper: 
Toward Away Across Average  
109.03 75.56 93.10 77.26

Could you please point me to some directions that I can generate the same numbers that your reported? 

Thank you so much,

**Comment by sde123** [comment]
@trungmanhhuynh 
Hello, Did you occur the following problems when you run the command "python3 utils/run.py scripts/5fold.json run <gpu id>"?

"Written to experiments/5fold_191219_143815/191219_151658
Traceback (most recent call last):
  File "train_cv.py", line 55, in <module>
    True, "scale" in args.model, args.ego_type)
  File "/home/dai/code/human_prediction_first_view/2/fpl/utils/dataset.py", line 91, in __init__
    ego_dict = data["egomotion_dict"][vid]
KeyError: b'GOPR0234U20'"
Looking forward to your reply!
